blog/urls.py
from django.urls import path
from .views import blog_detail, blog_list

app_name = 'blog'

urlpatterns = [
    path('article<slug:slug>/', blog_detail, name='detail'),
    path("blog-list/", blog_list, name='list')
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

blog/forms.py
from main.models import Commentary
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Commentary
        fields = ['name', 'message', 'email', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            "class": "form-control",
            "placeholder": "",

        })

        self.fields['message'].widget.attrs.update({
            "class": "form-control",
            "placeholder": "",

        })

        self.fields['email'].widget.attrs.update({
            "class": "form-control",
            "placeholder": "",

        })

        self.fields['image'].widget.attrs.update({
            "class": "form-control",
            "placeholder": "",

        })

blog/views.py
from django.shortcuts import render, redirect, reverse
from main.models import Article, Commentary, Result, Tag, Category
from .forms import CommentForm
from django.contrib import messages
# Create your views here.


def blog_detail(request, slug):
    tags = Tag.objects.all()
    categories = Category.objects.all()
    pid = request.GET.get("pid")
    form = CommentForm()
    article = Article.objects.get(slug=slug)
    articles = Article.objects.order_by('-id')[:3]
    if request.method == "POST":
        comment = CommentForm(request.POST, files=request.FILES)
        if comment.is_valid():
            obj = comment.save(commit=False)
            obj.article = article
            if pid:
                obj.parent_comment = Commentary.objects.get(id=pid)
            obj.save()
            messages.success(request, "Comment sent successfully")
            reverse_url = reverse('blog:detail', args=[slug])
            return redirect(reverse_url)
    ctx = {
        "article": article,
        "form": form,
        "tags": tags,
        "categories": categories,
        "articles": articles,
    }
    return render(request, 'blog/single.html', ctx)


def blog_list(request):
    articles = Article.objects.all()
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    print(tag)
    if cat:
        articles = Article.objects.filter(category__name__exact=cat)
    if tag:
        articles = Article.objects.filter(tag__name__exact=tag)
    ctx = {
        "articles": articles,
    }
    return render(request, 'blog/blog.html', ctx)

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}





{% block content %}
<section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center mb-5 pb-5">
                <div class="col-md-7 heading-section text-center ftco-animate">
                    <h1 class="big big-2">Blog</h1>
                    <h2 class="mb-4">Blog list</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                </div>
            </div>
            <div class="row d-flex">
                {% for article in articles %}



                    <div class="col-md-4 d-flex ftco-animate">
                        <div class="blog-entry justify-content-end">
                            <a href="../blog/single.html" class="block-20"
                               style="background-image: url({{ article.image.url }});">
                            </a>
                            <div class="text mt-3 float-right d-block">
                                <h3 class="heading"><a
                                        href="{% url 'blog:detail' article.slug %}">{{ article.title }}</a></h3>
                                <div class="d-flex align-items-center mb-3 meta">
                                    <p class="mb-0">
                                        <span class="mr-2">{{ article.created_date }}</span>
                                        <a href="#" class="mr-2">{{ article.author }}</a>
                                        <a href="#" class="meta-chat"><span
                                                class="icon-chat"></span>{{ article.comments.count }}</a>
                                    </p>
                                </div>
                                <p>A small river named Duden flows by their place and supplies it with the necessary
                                    regelialia.</p>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>
</section>
{% endblock %}

templates/blog/single.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <style>
        .tagcloud a {
            color: black !important;
            border: 1px solid #000000 !important;
        }
    </style>


    <div class="hero-wrap js-fullheight">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight justify-content-center align-items-center">
                <div class="col-lg-10 ftco-animate d-flex align-items-center">
                    <div class="text text-center">
                        <h1 class="mb-3 bread">Blog Single Post</h1>
                        <p class="breadcrumbs"><span class="mr-2"><a href="index-2.html">Home <i
                                class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a
                                href="{% url 'blog:list' %}">Blog <i
                                class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                                class="ion-ios-arrow-forward"></i></span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 ftco-animate">
                    <h2 class="mb-3">{{ article.title }}</h2>

                    <img src="{{ article.image.url }}" alt class="img-fluid">
                    </p>
                    <p>{{ article.content }}</p>

                    {% if article.sub_articles %}
                        {% for sub_article in article.sub_articles.all %}


                            <h2 class="mb-3 mt-5">{{ sub_article.title }}</h2>
                            <p>
                                <img src="{% if sub_article.image %}
                                	{{ sub_article.image.url }}
                                {% endif %} " alt class="img-fluid">
                            </p>
                            <p>{{ sub_article.content }}.</p>

                        {% endfor %}

                    {% endif %}
                    <div class="tag-widget post-tag-container mb-5 mt-5">
                        {% for tag in article.tag.all %}
                            <div class="tagcloud">
                                <a href="{% url 'blog:list' %}?tag={{ tag.name }}"
                                   class="tag-cloud-link">{{ tag.name }}</a>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="about-author d-flex p-4 bg-light">
                        <div class="bio mr-5">
                            <img src="{{ article.author.image.url }}" alt="Image placeholder" class="img-fluid mb-4">
                        </div>
                        <div class="desc">
                            <h3>{{ article.author.name }}</h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                                necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa
                                sapiente
                                consectetur similique, inventore eos fugit cupiditate numquam!</p>
                        </div>
                    </div>
                    <div class="pt-5 mt-5">
                        <h3 class="mb-5">{{ article.comments.count }} Comments</h3>
                        <ul class="comment-list">
                            {% if article.comments.count %}



                                {% for comment in article.comments.all %}
                                    {% if not comment.top_level_comment %}
                                        <li class="comment">
                                            <div class="vcard bio">
                                                <img src="{% if comment.image %}{{ comment.image.url }}{% else %}{% static 'images/comment/f_74864a2fb73a152b.jpeg' %}{% endif %}" alt="Image placeholder">
                                            </div>
                                            <div class="comment-body">
                                                <h3>{{ comment.name }}</h3>
                                                <div class="meta">{{ comment.created_date }}</div>
                                                <p>{{ comment.message }}</p>
                                                <p>
                                                    <a href="{% url 'blog:detail' article.slug %}?pid={{ comment.id }}#CommentForm"
                                                       class="reply">Reply</a></p>
                                            </div>
                                        </li>
                                    {% endif %}

                                    {% if comment.children %}
                                        {% for child in comment.children.all %}
                                            <li class="comment">
                                                <ul class="children">
                                                        <div class="vcard bio">
                                                            <img src="{% if child.image %}{{ child.image.url }}{% else %}{% static 'images/comment/f_74864a2fb73a152b.jpeg' %}{% endif %}"
                                                                 alt="Image placeholder">
                                                        </div>

                                                        <div class="comment-body">
                                                            <h3>{{ child.name }}</h3>

                                                            <div class="meta">{{ child.created_date }}</div>
                                                            <p>{{ child.message }}</p>
                                                            <p><a
                                                                    href="{% url 'blog:detail' article.slug %}?pid={{ child.id }}#CommentForm"
                                                                    class="reply">Reply</a></p>
                                                        </div>
                                                </ul>
                                            </li>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}

                            {% endif %}
                        </ul>

                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form method="post" enctype="multipart/form-data" id="CommentForm" class="p-5 bg-light">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="name">Name *</label>
                                    {{ form.name }}
                                    {#                                <input type="text" class="form-control" id="name">#}
                                </div>
                                <div class="form-group">
                                    <label for="email">Email *</label>
                                    {{ form.email }}
                                    {#                                <input type="email" class="form-control" id="email">#}
                                </div>
                                <div class="form-group">
                                    <label for="website">Image</label>
                                    {{ form.image }}
                                    {#                                <input type="url" class="form-control" id="website">#}
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    {{ form.message }}
                                    {#                                <textarea name id="message" cols="30" rows="10" class="form-control"></textarea>#}
                                </div>
                                <div class="form-group">
                                    <button class="btn py-3 px-4 btn-primary" type="submit">Post Comment</button>
                                    {#                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">#}
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 sidebar ftco-animate">
                    <div class="sidebar-box">
                        <form action="#" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" class="form-control" placeholder="Search...">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Categories</h3>
                        <ul class="categories">
                            {% for category in categories %}



                                <li><a href="{% url 'blog:list' %}?cat={{ category.name }}">{{ category.name }}
                                    <span>{{ category.categories.count }}</span></a>
                                </li>

                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Recent Blog</h3>
                        {% for article in articles %}
                            <div class="block-21 mb-4 d-flex">
                                <a class="blog-img mr-4" style="background-image: url({{ article.image.url }});"></a>
                                <div class="text">
                                    <h3 class="heading"><a
                                            href="{% url 'blog:detail' article.slug %}">{{ article.title }}</a></h3>
                                    <div class="meta">
                                        <div><a href="#"><span
                                                class="icon-calendar"></span> {{ article.created_date|date:"F d, Y" }}
                                        </a></div>
                                        <div><a href="#"><span class="icon-person"></span> {{ article.author }}</a>
                                        </div>
                                        <div><a href="#"><span class="icon-chat"></span>{{ article.comments.count }}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}


                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar">Tag Cloud</h3>
                        <div class="tagcloud">
                            {% for tag in tags %}
                                <a href="{% url 'blog:list' %}?tag={{ tag.name }}"
                                   class="tag-cloud-link">{{ tag.name }}</a>
                            {% endfor %}

                        </div>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3 class="heading-sidebar"></h3>
                        {% for article in articles %}
                            <p><img width="500px" src="{{ article.image.url }}" alt=""></p>
                            <a href="{% url 'blog:detail' article.slug %}"><p>{{ article.title }}</p></a>

                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}