blog/urls.py
from django.urls import path
from .views import blog_detail, blog_list

app_name = 'blog'

urlpatterns = [
    path('article<slug:slug>/', blog_detail, name='detail'),
    path("blog-list/", blog_list, name='list')
]

config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import home_view

app_name = 'main'

urlpatterns = [
    path('', home_view, name='index'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/ronaldo/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 27 Jan 2024 13:19:21 GMT -->
<head>
<title>Ronaldo - Free Bootstrap 4 Template by Colorlib</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'css/aos.css' %}">
<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script nonce="b9a8b00d-93ff-4311-bd87-529d49e5c218">try { (function(w,d){!function(b$,ca,cb,cc){b$[cb]=b$[cb]||{};b$[cb].executed=[];b$.zaraz={deferred:[],listeners:[]};b$.zaraz.q=[];b$.zaraz._f=function(cd){return async function(){var ce=Array.prototype.slice.call(arguments);b$.zaraz.q.push({m:cd,a:ce})}};for(const cf of["track","set","debug"])b$.zaraz[cf]=b$.zaraz._f(cf);b$.zaraz.init=()=>{var cg=ca.getElementsByTagName(cc)[0],ch=ca.createElement(cc),ci=ca.getElementsByTagName("title")[0];ci&&(b$[cb].t=ca.getElementsByTagName("title")[0].text);b$[cb].x=Math.random();b$[cb].w=b$.screen.width;b$[cb].h=b$.screen.height;b$[cb].j=b$.innerHeight;b$[cb].e=b$.innerWidth;b$[cb].l=b$.location.href;b$[cb].r=ca.referrer;b$[cb].k=b$.screen.colorDepth;b$[cb].n=ca.characterSet;b$[cb].o=(new Date).getTimezoneOffset();if(b$.dataLayer)for(const cm of Object.entries(Object.entries(dataLayer).reduce(((cn,co)=>({...cn[1],...co[1]})),{})))zaraz.set(cm[0],cm[1],{scope:"page"});b$[cb].q=[];for(;b$.zaraz.q.length;){const cp=b$.zaraz.q.shift();b$[cb].q.push(cp)}ch.defer=!0;for(const cq of[localStorage,sessionStorage])Object.keys(cq||{}).filter((cs=>cs.startsWith("_zaraz_"))).forEach((cr=>{try{b$[cb]["z_"+cr.slice(7)]=JSON.parse(cq.getItem(cr))}catch{b$[cb]["z_"+cr.slice(7)]=cq.getItem(cr)}}));ch.referrerPolicy="origin";ch.src="../../cdn-cgi/zaraz/sd0d9.js?z="+btoa(encodeURIComponent(JSON.stringify(b$[cb])));cg.parentNode.insertBefore(ch,cg)};["complete","interactive"].includes(ca.readyState)?zaraz.init():b$.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document) } catch (err) {
      console.error('Failed to run Cloudflare Zaraz: ', err)
      fetch('/cdn-cgi/zaraz/t', {
        credentials: 'include',
        keepalive: true,
        method: 'GET',
      })
    };</script></head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">



    {% if messages %}
    <div id="django-messages" class="">
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="message-success">{{ message }}</div>
            {% elif message.tags == 'error' %}
                <div class="message-danger">{{ message }}</div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}



        <style>
    #django-messages div[class^=message] {
  width: 100%;
  padding: 40px 15px;
  border-radius: 8px;
  border: 2px solid;
  color: #fff;
  font-weight: 700;
  line-height: 18px;
  z-index: 999;
}
#django-messages {
  position: sticky !important;
  z-index: 4;
  overflow: hidden;
}
#django-messages .message-success {
  background-color: forestgreen;
  border-color: darkgreen;
}
#django-messages .message-error {
  background-color: red;
  border-color: darkred;
}
.hide {
  animation-name: hide_slide_show;
  animation-duration: 2s;
  animation-fill-mode: forwards;
}

@keyframes hide_slide_show {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
    visibility: hidden;
  }

}
    </style>


{% include 'navbar.html' %}

{% block content %}

{% endblock %}

{% include 'footer.html' %}

<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"84c149723b175e05","b":1,"version":"2024.1.0","token":"cd0b4b3a733644fc843ef0b185f98241"}' crossorigin="anonymous"></script>
</body>

    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $('#django-messages').addClass('hide');
            }, 3000);
        });
    </script>


<!-- Mirrored from preview.colorlib.com/theme/ronaldo/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 27 Jan 2024 13:20:00 GMT -->
</html>

templates/footer.html
<footer class="ftco-footer ftco-section">
<div class="container">
<div class="row mb-5">
<div class="col-md">
<div class="ftco-footer-widget mb-4">
<h2 class="ftco-heading-2">About</h2>
<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
</ul>
</div>
</div>
<div class="col-md">
<div class="ftco-footer-widget mb-4 ml-md-4">
<h2 class="ftco-heading-2">Links</h2>
<ul class="list-unstyled">
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Home</a></li>
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>About</a></li>
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Services</a></li>
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Projects</a></li>
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Contact</a></li>
</ul>
</div>
</div>
<div class="col-md">
<div class="ftco-footer-widget mb-4">
<h2 class="ftco-heading-2">Services</h2>
<ul class="list-unstyled">
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Design</a></li>
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Web Development</a></li>
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Business Strategy</a></li>
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Data Analysis</a></li>
<li><a href="#"><span class="icon-long-arrow-right mr-2"></span>Graphic Design</a></li>
</ul>
</div>
</div>
<div class="col-md">
<div class="ftco-footer-widget mb-4">
<h2 class="ftco-heading-2">Have a Questions?</h2>
<div class="block-23 mb-3">
<ul>
<li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
<li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
<li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span class="__cf_email__" data-cfemail="8ae3e4ece5caf3e5fff8eee5e7ebe3e4a4e9e5e7">[email&#160;protected]</span></span></a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="row">
<div class="col-md-12 text-center">
<p>
Copyright &copy;<script data-cfasync="false" src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com/" target="_blank">Colorlib</a>
</p>
</div>
</div>
</div>
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar">
<div class="container">
<a class="navbar-brand" href="/"><span>B</span>exruz</a>
<button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
<span class="oi oi-menu"></span> Menu
</button>
<div class="collapse navbar-collapse" id="ftco-nav">
<ul class="navbar-nav nav ml-auto">

<li class="nav-item"><a href="{% url 'main:index' %}#home-section" class="nav-link"><span>Home</span></a></li>
<li class="nav-item"><a href="{% url 'main:index' %}#about-section" class="nav-link"><span>About</span></a></li>
<li class="nav-item"><a href="{% url 'main:index' %}#resume-section" class="nav-link"><span>Resume</span></a></li>
<li class="nav-item"><a href="{% url 'main:index' %}#services-section" class="nav-link"><span>Services</span></a></li>
<li class="nav-item"><a href="{% url 'main:index' %}#projects-section" class="nav-link"><span>Projects</span></a></li>
<li class="nav-item"><a href="{% url 'main:index' %}#blog-section" class="nav-link"><span>My Blog</span></a></li>
<li class="nav-item"><a href="{% url 'main:index' %}#contact-section" class="nav-link"><span>Contact</span></a></li>

</ul>
</div>
</div>
</nav>